main/urls.py
from django.urls import path
from .views import user_profile

app_name = "register"
urlpatterns = [
    # path('register/', register, name="register"),
    path('user/<int:user_id>/profile', user_profile, name="userprofile"),
    path('login/',)
]

zdrowie/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('health/',include('health.urls')),
    path('', include('register.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('login/',)
]

main/models.py
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField("auth.User", on_delete=models.CASCADE)
    bio = models.TextField()

    class Meta:
        verbose_name = "Użytkownik"
        verbose_name_plural = "Użytkownicy"

main/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, HTML, ButtonHolder
from django import forms

from main.models import UserProfile


class ContactForm(forms.Form):
    email = forms.EmailField(label="Adres e-mail:")
    title = forms.CharField(label="Tytuł:")
    content = forms.CharField(widget=forms.Textarea, label="Treść wiadomości:")
    send_to_me = forms.BooleanField(required=False, label="Wyślij do mnie")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.from_action = 'contact'
        self.helper.layout = Layout(
            Fieldset(
                'Dane kontaktowe',
                'email',
            ),
            Fieldset(
                'Zawartość',
                'title',
                'content'
            ),
            Fieldset(
                'Dodtakowe',
                HTML("Zaznacz jeśli chcesz by wysłać kopię wiadomości do Ciebie"),
                'send_to_me'
            ),
            ButtonHolder(
                Submit('submit', 'Wyślij', css_class='btn btn-primary'),
                css_class="d-flex justify-content-end"
            )
        )


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['user', 'bio']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = 'profile'
        self.helper.add_input(Submit('submit', 'Wyślij'))

main/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from django.shortcuts import render, get_object_or_404
from main.forms import ContactForm, UserProfileForm
from . import services
from django.contrib.auth import get_user_model
from django.contrib.auth import  authenticate, login

def contact(request):
    if request.method == "POST":
        form = ContactForm(data=request.POST)
        if form.is_valid():
            services.send_message(form.cleaned_data)
            return HttpResponseRedirect(reverse("main:contact"))
    else:
        form = ContactForm()
    return render(request, "main/contact.html", {"form":form})


def user_profile(request, user_id):
    user = get_object_or_404(get_user_model(), id=user_id)
    if request.method == "POST":
        try:
            profile = user.userprofile
            form = UserProfileForm(request.POST, instance=profile)
        except AttributeError: pass
        if form.is_valid(): form.save()
    else:
        try:
            profile = user.userprofile
            form = UserProfileForm(instance=profile)
        except AttributeError:
            form = UserProfileForm(initial={"user": user, "bio": ""})
        if request.user != user:
            for field in form.fields:
                form.fields[field].disabled = True
            form.helper.inputs = []
    return render(request, 'userprofile.html', {'form': form})


def login(request):
    username = request.POST('user')

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Strona główna {% endblock %}</title>
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
<div class="container">

    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
            <img src="https://pywww.pl/assets/graphics/logo.png">
          <span class="fs-4">Aplikacja do rejestrowania pomiarów zdrowotnych</span>
      </a>

    <div class="col-md-3 text-end">
        {%  if user.is_authenticated %}
            <a type ="button" class="btn btn-outline-primary me-2" href="{% url "logout" %}">Wyloguj</a>
            <p>jesteś zalogowany/a jako {{ request.user }}</p>
        {% else %}
            <a type="button" class="btn btn-outline-primary me-2" href="{% url "login" %}">Zaloguj</a>
            <a type="button" class="btn btn-primary" href="{% url "register:register" %}">Zarejestruj</a>
            <p>nie jesteś zalogowany/a</p>
        {% endif %}
    </div>


      <ul class="nav nav-pills">
{#        <li class="nav-item"><a href="{% url 'main:home' %}" class="nav-link active" aria-current="page">Strona główna</a></li>#}
{#        <li class="nav-item"><a href="{% url 'health:health_view' %}" class="nav-link">Lista pomiarów</a></li>#}
{#        <li class="nav-item"><a href="{% url 'main:contact' %}" class="nav-link">kontakt</a></li>#}
{#        <li class="nav-item"><a href="{% url 'main:hello' %}" class="nav-link">O stronie</a></li>#}
{#          {% if user.id %}#}
{#          <li class="nav-item"> <a href="{% url 'main:userprofile' user.id %}" class="nav-link">Mój profil ({{ request.user }}) </a> </li>#}
{#        {% endif %}#}
      </ul>
    </header>
</div>

{% block header %}
{% endblock %}

<div class="container">
    {% block content %}
    {% endblock %}
</div>

{% block footer %}
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-muted"> 2022 A.M.W. </p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-2" width="5" height="4"><use xlink:href="#bootstrap"></use></svg>
        <img src="https://pywww.pl/assets/graphics/logo.png">
    </a>

    <ul class="nav col-md-4 justify-content-end">
{#      <li class="nav-item"><a href="{% url 'main:home' %}" class="nav-link px-2 text-muted">Strona główna</a></li>#}
{#       <li class="nav-item"><a href="{% url 'main:hello' %}" class="nav-link px-2 text-muted">O stronie</a></li>#}
{#        <li class="nav-item"><a href="{% url 'main:contact' %}" class="nav-link px-2 text-muted">Kontakt</a></li>#}
    </ul>
  </footer>
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

{%  block additional_scripts %}
{%  endblock %}

</body>
</html>

main/templates/contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Kontakt {% endblock %}
    {% block header %}
    {% endblock %}

{% block content %}
    <h2>Kontakt:</h2>
    {% crispy form form.helper %}
{#    <form method = "POST">#}
{#    {% csrf_token %}#}
{#    {{ form|crispy }}#}
{#    <button type=""submit"#}
{#    class = "btn btn-primary">Wyślij</button>#}
{#    </form>#}
{% endblock %}

main/templates/login.html
{% extends "base.html" %}

{% block title %} Login {% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <p><h4>Logowanie:</h4></p>
        <form method="POST" class="form-group">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Zaloguj</button>
</form>
{% endblock %}

main/templates/logout.html
{% extends "base.html" %}

{% block title %} Logout {% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <p><h4>Logowanie:</h4></p>
        <form method="POST" class="form-group">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Wyloguj</button>
</form>
{% endblock %}

main/templates/userprofile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Profil {% endblock %}
{% block content %}
    <p><h4>Edytuj profil:</h4></p>
{% crispy form %}
    <div>

    <ol>

    </ol>
    </div>
{% endblock %}